import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// docs/ ディレクトリ構成と frontmatter (sidebar_position) から自動生成する。
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
